# Generated by Django 5.0.6 on 2024-05-27 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_alter_team_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strategy_type', models.CharField(choices=[('OFF', 'Offense'), ('DEF', 'Defense')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='defense_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense_teams', to='roster.strategy'),
        ),
        migrations.AddField(
            model_name='team',
            name='offense_strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offense_teams', to='roster.strategy'),
        ),
    ]
